config/routes.rb
Projects::Application.routes.draw do
  get "pages/about"
  get "pages/contact"

  root 'projects#index'

  resources :projects do
    resources :products
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def create
	@project = Project.find(params[:project_id])
    @product = @project.products.create(product_params)
    redirect_to project_path(@project)
	end


private

  def product_params
    params.require(:product).permit(:name, :quantity)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.all
	end

	def show
		@project = Project.find(params[:id])
		@product = Product.new
	end

	def new
		@project = Project.new
	end

	def create
		Project.create(project_params)
		redirect_to projects_path
	end


private

	def project_params
		params.require(:project).permit(:name, :description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="#">Projects</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Browse Projects", projects_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right links">
        <li></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projects</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>All about this website</p>

app/views/pages/contact.html.erb
<h1>Contact Me</h1>
<p>Please contact me</p>

app/views/projects/index.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
<h1>All Projects</h1><br />
	<% @projects.each do |project| %>
		<h2><%= link_to project.name, project_path(project) %></h2><br />
		<p><%= project.description %></p>
	<% end %>
</div>

app/views/projects/new.html.erb
<h1>Create a Project</h1>

<%= simple_form_for @project do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', :class => 'btn btn-primary' %>
<% end %>

app/views/projects/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1><%= @project.name %></h1>
	<p><%= @project.description %></p>

<div class="clear"></div>
<%= simple_form_for @product, :url => project_products_path(@project) do |f| %>
    <%= f.input :name %>
    <%= f.input :quantity %>
    <br />
    <%= f.submit 'Create', :class => 'btn btn-primary' %>
<% end %>
</div>
<div class="clear"></div>
<h1>Products</h1>

<% @project.products.each do |product| %>
  <ul>
      <li><%= product.name %></b> -
        <%= product.quantity %></li>
  </ul>
<% end %>